#!/usr/bin/env python3
"""
build_ministack_mask.py
==========================
Stage 2 of 6 (functional-to-structural registration).

Stacks the per-plane valid-data masks (aligned_planes_valid_mask/, written by
correct_interplane_drift.py) into a mini-stack NIfTI with the exact same
geometry as functional_ministack.nii.gz. Used as `moving_mask` in
ants.registration (register_ministack_to_structural.py) so the correlation
metric is not corrupted by the ragged empty borders that drift-correction
introduces -- each plane is shifted by a different amount and so leaves a
different empty margin; without a mask the optimizer can end up sampling
mostly in those zero regions and diverge.

Reads:
  - data_for_upload/02_functional_to_structural_registration/stage1_ministack/
    aligned_planes_valid_mask/meanImg_z*.tif

Writes:
  - data_for_upload/02_functional_to_structural_registration/stage1_ministack/
    functional_ministack_mask.nii.gz (intermediate; consumed by
    register_ministack_to_structural.py, not itself redistributed since it is
    cheaply regenerated by this script)

Run order: after correct_interplane_drift.py, before
register_ministack_to_structural.py.

Environment: antspy env (nibabel, numpy, tifffile).
"""

import glob
import os
import re

import nibabel as nib
import numpy as np
import tifffile

DATA_ROOT = os.environ.get("PIPELINE_DATA_ROOT") or os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data_for_upload"))

STAGE1_DIR = os.path.join(DATA_ROOT, "02_functional_to_structural_registration", "stage1_ministack")
MASK_DIR = os.path.join(STAGE1_DIR, "aligned_planes_valid_mask")
OUT_PATH = os.path.join(STAGE1_DIR, "functional_ministack_mask.nii.gz")

XY_SPACING_UM = 1.40625
Z_SPACING_UM = 10.0


def main():
    paths = sorted(glob.glob(os.path.join(MASK_DIR, "meanImg_z*.tif")))
    assert len(paths) == 36, f"expected 36 masks, found {len(paths)}"

    depths, planes_xy = [], []
    for p in paths:
        m = re.search(r"z(\d+)\.tif$", p)
        depths.append(int(m.group(1)))
        img_yx = tifffile.imread(p)
        planes_xy.append(img_yx.T)  # (Y,X) -> (X,Y), already rotated+corrected

    volume_xyz = np.stack(planes_xy, axis=2).astype(np.uint8)
    print(f"Mask mini-stack shape (X,Y,Z): {volume_xyz.shape}, nonzero frac: {(volume_xyz > 0).mean():.4f}")

    affine = np.diag([XY_SPACING_UM, XY_SPACING_UM, Z_SPACING_UM, 1.0])
    out_img = nib.Nifti1Image(volume_xyz, affine)
    out_img.header.set_data_dtype("uint8")
    out_img.header.set_xyzt_units(xyz="micron")
    out_img.set_sform(affine, code=1)
    out_img.set_qform(affine, code=1)
    nib.save(out_img, OUT_PATH)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
