#!/usr/bin/env python3
"""
diag_stageB_block_displacement.py
=====================================
Stage 2 of 6 (functional-to-structural registration) -- validation/QC
companion to build_stageB_plane_corrections.py.

Dense measurement of the functional-vs-structural local residual across all
32 included native planes, via local block-matching. The functional channel
(ch1) and the structural channel pulled onto each native plane via Stage 2's
affine (ch2) are the SAME imaging modality (2P GCaMP, same fish), unlike the
confocal-vs-2P case in stage 03, so local block-matching is reliable here in
a way it would not be across modalities.

For each plane: build ch1/ch2 using the same tilted-slab technique used
elsewhere in this stage (Stage 2's affine only -- this diagnostic is purely
about the Stage 2 residual, independent of any other stage). Divide into a
grid of blocks; for blocks with enough signal in both channels, measure local
displacement via skimage.registration.phase_cross_correlation with
upsampling, keeping only confident matches (low normalized RMS error).
Aggregates into a per-plane summary, useful for confirming that
build_stageB_plane_corrections.py's per-plane correction generalizes across
the whole frame rather than only at the single central template location it
measures directly.

Reads:
  - data_for_upload/01_suite2p_preprocessing/mean_images/meanImg_z*.tif
  - data_for_upload/03_structural_to_template_registration/stage0_geometry_fixed/
    02F_stack_ras_cropped.nii.gz
  - data_for_upload/02_functional_to_structural_registration/stage1_ministack/
    functional_ministack.nii.gz (for header geometry only, via compute_seed_origin)
  - data_for_upload/02_functional_to_structural_registration/stage2_registration/
    fwd_final_affine.mat

Writes:
  - data_for_upload/02_functional_to_structural_registration/stage2_registration/
    diag_stageB_block_results.npy (diagnostic only; not required by any
    downstream step, regenerated by re-running this script)

Run order: after build_stageB_plane_corrections.py.

Environment: antspy env (ants, nibabel, numpy, scikit-image, tifffile,
matplotlib).
"""

import os
import sys

import ants
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
import tifffile
from skimage.registration import phase_cross_correlation

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from register_ministack_to_structural import compute_seed_origin  # noqa: E402

DATA_ROOT = os.environ.get("PIPELINE_DATA_ROOT") or os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data_for_upload"))

STAGE2_DIR_NAME = "02_functional_to_structural_registration"
MEAN_IMG_DIR = os.path.join(DATA_ROOT, "01_suite2p_preprocessing", "mean_images")
STRUCTURAL_PATH = os.path.join(DATA_ROOT, "03_structural_to_template_registration",
                                "stage0_geometry_fixed", "02F_stack_ras_cropped.nii.gz")
STAGE_B_AFFINE = os.path.join(DATA_ROOT, STAGE2_DIR_NAME, "stage2_registration", "fwd_final_affine.mat")
STAGE_B_MINISTACK = os.path.join(DATA_ROOT, STAGE2_DIR_NAME, "stage1_ministack", "functional_ministack.nii.gz")
OUT_NPY = os.path.join(DATA_ROOT, STAGE2_DIR_NAME, "stage2_registration", "diag_stageB_block_results.npy")

XY_SPACING_UM = 1.40625
Z_SPACING_UM = 10.0
DIRECTION = np.array([[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, 1.0]])
EXCLUDED_IDX = {0, 1, 2, 3}

BLOCK = 80          # block size in pixels
STRIDE = 60          # stride between block centers (some overlap)
MIN_SIGNAL_PCTL = 60  # block must have signal above this percentile of the whole frame in BOTH channels
UPSAMPLE = 20
MAX_ERROR = 0.7       # phase_cross_correlation normalized RMS error threshold (lower = more confident)


def unrot(a):
    return np.rot90(a.T, k=-1)


def main():
    mini = nib.load(STAGE_B_MINISTACK)
    mini_spacing = np.array(mini.header.get_zooms()[:3])
    seed_origin = compute_seed_origin(mini.shape, mini_spacing)

    structural = ants.image_read(STRUCTURAL_PATH)

    paths = sorted(
        [p for p in os.listdir(MEAN_IMG_DIR) if p.startswith("meanImg_z") and p.endswith(".tif")]
    )
    assert len(paths) == 36

    results = []  # list of dicts: depth, block centers, dy, dx, error

    for i, fn in enumerate(paths):
        if i in EXCLUDED_IDX:
            continue
        depth = int(fn.replace("meanImg_z", "").replace(".tif", ""))

        img_yx = tifffile.imread(os.path.join(MEAN_IMG_DIR, fn))
        plane_xy = np.rot90(img_yx, 1).T.astype(np.float32)

        z_i_um = float(seed_origin[2] + i * Z_SPACING_UM)
        plane_origin_um = (-float(seed_origin[0]), -float(seed_origin[1]), z_i_um)
        plane_origin = tuple(v / 1000.0 for v in plane_origin_um)
        plane_spacing = tuple(v / 1000.0 for v in (XY_SPACING_UM, XY_SPACING_UM, Z_SPACING_UM))

        plane_slab = ants.from_numpy(
            plane_xy[:, :, np.newaxis], origin=plane_origin,
            spacing=plane_spacing, direction=DIRECTION,
        )
        ch2_struct = ants.apply_transforms(
            fixed=plane_slab, moving=structural,
            transformlist=[STAGE_B_AFFINE], whichtoinvert=[True],
            interpolator="linear",
        ).numpy()[:, :, 0]

        ch1 = unrot(plane_xy).astype(np.float32)
        ch2 = unrot(ch2_struct).astype(np.float32)

        h, w = ch1.shape
        thresh1 = np.percentile(ch1[ch1 > 0], MIN_SIGNAL_PCTL) if np.any(ch1 > 0) else 0
        thresh2 = np.percentile(ch2[ch2 > 0], MIN_SIGNAL_PCTL) if np.any(ch2 > 0) else 0

        block_results = []
        for y0 in range(0, h - BLOCK, STRIDE):
            for x0 in range(0, w - BLOCK, STRIDE):
                b1 = ch1[y0:y0+BLOCK, x0:x0+BLOCK]
                b2 = ch2[y0:y0+BLOCK, x0:x0+BLOCK]
                if b1.max() < thresh1 or b2.max() < thresh2:
                    continue
                if b1.std() < 1e-3 or b2.std() < 1e-3:
                    continue
                try:
                    shift, error, _ = phase_cross_correlation(b2, b1, upsample_factor=UPSAMPLE, normalization=None)
                except Exception:
                    continue
                if error > MAX_ERROR:
                    continue
                if np.hypot(*shift) > 30:  # implausibly large local shift, discard
                    continue
                block_results.append({
                    "yc": y0 + BLOCK/2, "xc": x0 + BLOCK/2,
                    "dy": shift[0], "dx": shift[1], "error": error,
                })

        results.append({"depth": depth, "idx": i, "blocks": block_results, "ch1": ch1, "ch2": ch2})
        n_conf = len(block_results)
        if n_conf > 0:
            dys = np.array([b["dy"] for b in block_results])
            dxs = np.array([b["dx"] for b in block_results])
            print(f"plane {i} z={depth}: {n_conf} confident blocks, "
                  f"median dy={np.median(dys):.2f} dx={np.median(dxs):.2f} "
                  f"std dy={dys.std():.2f} dx={dxs.std():.2f}")
        else:
            print(f"plane {i} z={depth}: 0 confident blocks")

    os.makedirs(os.path.dirname(OUT_NPY), exist_ok=True)
    np.save(OUT_NPY, np.array(results, dtype=object), allow_pickle=True)
    print(f"\nsaved {OUT_NPY}")


if __name__ == "__main__":
    main()
